{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource-reaper.fullname" . }}
  labels:
    {{- include "resource-reaper.labels" . | nindent 4 }}
rules:
  # Allow controller to watch all resources
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "delete"]
  # Allow leader election
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource-reaper.fullname" . }}
  labels:
    {{- include "resource-reaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource-reaper.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource-reaper.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
