apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-reaper
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-reaper
  template:
    metadata:
      labels:
        app: resource-reaper
    spec:
      serviceAccountName: resource-reaper-sa
      containers:
      - name: resource-reaper
        image: resource-reaper:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-reaper-sa
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resource-reaper-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-reaper-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-reaper-role
subjects:
- kind: ServiceAccount
  name: resource-reaper-sa
  namespace: kube-system
