apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-reaper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-reaper
  template:
    metadata:
      labels:
        app: resource-reaper
    spec:
      serviceAccountName: resource-reaper
      containers:
      - name: controller
        image: resource-reaper:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
