apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
  annotations:
    resource-reaper/ttl: "720h"  # ConfigMap will be deleted after 30 days
data:
  app.properties: |
    environment=staging
    log.level=INFO
    feature.flag=true
