apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
  annotations:
    resource-reaper/ttl: "1h"  # Pod will be deleted after 1 hour
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
