apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  annotations:
    resource-reaper/ttl: "168h"  # Service will be deleted after 1 week
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
