# Default values for resource-reaper
replicaCount: 1

image:
  repository: ghcr.io/abhinavgrover15/resource-reaper
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Controller configuration
controller:
  leaderElection:
    enabled: true
  metrics:
    enabled: true
    port: 8080
  logLevel: info
  logFormat: json
